const express = require('express');
const productController = require('../controller/ProductController');
const verifyUser = require('../middleware/AuthMiddleware');
const router = express.Router();
//router.post('/create',verifyUser, productController.create);
router.post('/create', productController.create);
router.get('/find-by-id',verifyUser, productController.findById);
//router.delete('/delete-by-id/:id',verifyUser, productController.deleteById);
router.delete('/delete-by-id/:id', productController.deleteById);
router.put('/update',verifyUser, productController.update);
//router.get('/find-all',verifyUser, productController.findAll);
router.get('/find-all', productController.findAll);
router.get('/find-all-min', productController.findAllMin);
router.get('/find-all-count', productController.findCount);
module.exports=router;